config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :bookings
  resources :venues
  resources :artists
  resources :events
  resources :pages
  resource :session do
    get :link_calendar, :on => :member
  end
  resources :goals
  resources :payments, :param => :transaction_id
  resources :funds
  resources :users
  resources :uploads

  get '/auth/:provider/callback', to: 'sessions#create'
  
  root :to => 'pages#index'
  #root :to => 'funds#index'
end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id                            :integer          not null, primary key
#  name                          :string
#  created_at                    :datetime         not null
#  updated_at                    :datetime         not null
#  image_uid                     :string
#  email                         :string
#  image_name                    :string
#  logo_uid                      :string
#  logo_name                     :string
#  representation_agreed_at      :datetime
#  google_calendar_token         :string
#  google_calendar_refresh_token :string
#  google_calendar_id            :string
#

class Artist < ApplicationRecord
  include Translatable

  has_many :user_relations, :as => 'relative'
  has_many :users, :through => :user_relations
  has_many :artist_events
  has_many :events, :through => :artist_events
  accepts_translations_for :bio
  dragonfly_accessor :image

  def representation_agreed=(value)
    if value
      self.representation_agreed_at = Time.now
    else
      # representation_agreed = nil # Can't undo an agreement
    end
  end
  
  def representation_agreed
    !representation_agreed_at.nil?
  end
  
  def user
    user_relations.is.first.try(:user)
  end
  
  def claim_by!(user)
    self.update(:representation_agreed => true)
    UserRelation.create(:relation => 'is', :user => user, :relative => self)
  end
  
  def managed_by?(user)
    return false unless user
    return true if UserRelation.where(:relation => 'is', :user => user).any?
    return true if user.admin?
    return true if user.bootstrap_artist_id == self.id
  end
  
  def default_price
    100000
  end

  def bookable?
    self.email.present?
  end
  
  def calendars
    @google_client ||= Signet::OAuth2::Client.new(
      client_id: ENV.fetch('GOOGLE_API_CLIENT_ID'),
      client_secret: ENV.fetch('GOOGLE_API_CLIENT_SECRET'),
      access_token: self.google_calendar_token,
      refresh_token: self.google_calendar_refresh_token,
      token_credential_uri: 'https://accounts.google.com/o/oauth2/token'
    )
    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = @google_client
    @calendar_list = service.list_calendar_lists
    @calendar_list
  end

end

app/controllers/artists_controller.rb
# == Schema Information
#
# Table name: artists
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy, :link_calendar]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
    @artist.update :representation_agreed => true if params[:agreed]      
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
    

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :email, :retained_image, :bio_ja, :bio_en, :representation_agreed, :google_calendar_token, :google_calendar_id)
    end
end

app/helpers/artists_helper.rb
# == Schema Information
#
# Table name: artists
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module ArtistsHelper
end

app/views/artists/_form.html.haml
= form_for(artist) do |f|
  - if artist.errors.any?
    #error_explanation
      %h2
        = pluralize(artist.errors.count, "error")
        prohibited this artist from being saved:
      %ul
        - artist.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
    
  -# .field
  -#   = f.label :representation_agreed
  -#   = f.check_box :representation_agreed
  .field
    = f.image_upload_field :image
  .field
    = f.translated_text_area :bio
  .field
    - if artist.google_calendar_token.present?
      
      .calendars
        %p Choose the calendar you want to use for availability
        %p
          = f.select :google_calendar_id, artist.calendars.items.collect { |calendar| [calendar.summary, calendar.id] }
      %p= link_to 'Unlink calendar from artist', artist_path(artist, :artist => {:google_calendar_token => nil}), :method => 'PUT', :data => {:confirm => 'Remove google calendar access?'}
    - elsif artist.persisted?
      = link_to 'Link to calendar', google_calendar_auth_path(artist)
  .actions
    = f.submit

app/views/artists/edit.html.haml
- if !@artist.representation_agreed
  .section.header
    .container-fluid
      %h1= t '.representation_agreement'
  .container-fluid
    = image_tag 'newsoundforjapantext2.png', :width => 600
    
    .intro_section
      %p
        %i.fa.fa-heart
        = t '.hello_artist', :name => @artist.name
    .description_section
      %p= t '.description'
    .features_section
      %p= t '.features'
      %ul
        %li
          %i.fa.fa-check
          = t '.feature1' #Personal, customizable and multilingual artist profile
        %li
          %i.fa.fa-check
          = t '.feature2' #Unbiased translations and mediation between languages
        %li
          %i.fa.fa-check
          = t '.feature3' #Automated booking system for promoters
        %li
          %i.fa.fa-check
          = t '.feature4' #No need for managers or management fees
        %li
          %i.fa.fa-check
          = t '.feature5' #Competetive rates and guarantees
        %li
          %i.fa.fa-check
          = t '.feature6' #Accept payments online using credit cards
    .call_to_action_section
      %p= t '.call_to_action'
      = link_to t('.agree', :name => @artist.name), url_for(:agreed => true), :class => 'button'
- else
  .section.header
    .container-fluid
      %h1 Edit Artist
      
  .container-fluid
    - if @artist.user
      This page is owned by #{@artist.user.name}
    - else
      .bootstrap
        %p 
          To claim this artist, use this link:
          = link_to 'Bootstrap me', new_user_path(:secret => make_secret(:bootstrap_artist_id => @artist.id))
    = render 'form', artist: @artist

app/views/artists/index.html.haml
.section.header
  .container-fluid
    - if @current_user
      .options
        = link_to "Join us", new_artist_path, :class => 'button'
    %h1 Artist Roster
  

.container-fluid
  .row
    - @artists.each do |artist|
      .artist.col-lg-4.col-md-6.col-sm-12
        .content
          .inner
            - if artist.image
              .image{:style=>"background-image:url(#{artist.image.thumb('600x600').url})"}
            - else
              .image.empty
            = link_to '', artist, :class => 'artist_link'
            .info
              .name
                = artist.name
              .booking
                = link_to 'Available', artist

app/views/artists/new.html.haml
.section.header
  .container-fluid
    %h1 New Artist

.container-fluid
  = render 'form', artist: @artist
  

app/views/artists/show.html.haml
.section.header
  .container-fluid
    .options
      = link_to 'Edit', edit_artist_path(@artist), :class => 'button' if @artist.managed_by?(@current_user)
    %h1
      = @artist.name
      - if @artist.user
        %i.fa.fa-check.brand
.section.availability
  .container-fluid
    - if @artist.bookable?
      .options
        = link_to 'Book now', new_booking_path(:booking => {:bookee_id => @artist, :bookee_type => @artist.class.name}), :class => 'button'
    - else
      %p= t '.unbookable'
    %h2 Availability
  
      
.section.bio  
  .container-fluid
    = sanitize @artist.bio, :tags => %w(iframe span p strong em img)
.section.news
  .container-fluid
    %h1 Upcoming Events
    - @artist.events.upcoming.each do |event|
      %p= link_to event.name, event
    - if @artist.events.upcoming.empty?
      %p Nothing happening
    
  -# = link_to 'Add Event', '#', :class => 'button add_event'
  
-# .add_to_event.modal
  -# %header Add to Event
  
  