config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :bookings
  resources :venues
  resources :artists
  resources :events
  resources :pages
  resource :session do
    get :link_calendar, :on => :member
  end
  resources :goals
  resources :payments, :param => :transaction_id
  resources :funds
  resources :users
  resources :uploads

  get '/auth/:provider/callback', to: 'sessions#create'
  
  root :to => 'pages#index'
  #root :to => 'funds#index'
end

app/models/booking.rb
# == Schema Information
#
# Table name: bookings
#
#  id                  :integer          not null, primary key
#  booker_id           :integer
#  bookee_id           :integer
#  price               :integer
#  currency            :string
#  bookee_confirmed_at :datetime
#  booker_confirmed_at :datetime
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  bookee_type         :string
#  event_id            :integer
#

class Booking < ApplicationRecord
  belongs_to :booker, :class_name => 'User'
  belongs_to :bookee, :polymorphic => true
  belongs_to :event
  
  validates :booker, :presence => true
  validates :bookee, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 50} # minimum JPY required by stripe
  
  accepts_nested_attributes_for :event
  
  scope :active, -> { joins(:event).where('events.start_at > ?', Time.now) }
  
  after_create do
    ApplicationMailer.booking_inquiry(self).deliver_later
    Message.create(:topicable => self, :text => 'Booking request has been received.')
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  # def index
  #   @bookings = Booking.all
  # end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new(booking_params)
    @booking.price = @booking.bookee.default_price
    @booking.event = Event.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @booking.booker = @current_user
    
    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if booking_params[:accept] && @booking.bookee.managed_by?(@current_user) && !@booking.bookee_confirmed_at
        @booking.event.artists.push(@booking.bookee) if @booking.bookee.is_a?(Artist)
        @booking.update :bookee_confirmed_at => Time.now
        # TODO: send email to booker
        return redirect_to :back, :notice => 'Offer accepted.'
      end
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:booker_id, :hotel_provided, :transportation_provided, :bookee_id, :bookee_type, :price, :currency, :bookee_confirmed_at, :booker_confirmed_at, :accept, :event_attributes => [:start_at])
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.haml
= form_for(booking) do |f|
  = f.hidden_field :bookee_id
  = f.hidden_field :bookee_type
  = f.hidden_field :currency, :value => 'JPY'
  - if booking.errors.any?
    #error_explanation
      %h2
        = pluralize(booking.errors.count, "error")
        prohibited this booking from being saved:
      %ul
        - booking.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :price
    = f.text_field :price
    JPY
  = f.fields_for :event do |ef|
    .field
      = ef.label :start_at
      = ef.text_field :start_at, :class => 'datepicker'
  .actions
    = f.submit

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Booker</th>
      <th>Bookee</th>
      <th>Price</th>
      <th>Currency</th>
      <th>Bookee confirmed at</th>
      <th>Booker confirmed at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.booker_id %></td>
        <td><%= booking.bookee_id %></td>
        <td><%= booking.price %></td>
        <td><%= booking.currency %></td>
        <td><%= booking.bookee_confirmed_at %></td>
        <td><%= booking.booker_confirmed_at %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.haml
.section.header
  .container-fluid
    %h1 Book #{@booking.bookee.name}
.section.guide
  .container-fluid
    %h2= t '.thanks', :artist => @booking.bookee.name # Thank you for your interest in %{artist}
    %p= t '.booking_guide' # You can book this artist for your event. This is how it usually goes:
    %p= t '.booking_step_1' # Make an offer
    %p= t '.booking_step_2' # Artist confirms the offer
    %p= t '.booking_step_3' # Make payment
    %p= t '.booking_step_4' # Enjoy the event
.section.form
  .container-fluid
    .nice_form
      = form_for(@booking) do |f|
        = f.hidden_field :bookee_id
        = f.hidden_field :bookee_type
        = f.hidden_field :currency, :value => 'JPY'
        - if @booking.errors.any?
          #error_explanation
            %h2
              = pluralize(@booking.errors.count, "error")
              prohibited this @booking from being saved:
            %ul
              - @booking.errors.full_messages.each do |message|
                %li= message
        = f.fields_for :event do |ef|
          .field
            = ef.label :start_at
            = ef.text_field :start_at, :class => 'datepicker'
        .field
          = f.label :price
          .inputs
            ¥
            = f.text_field :price, :class => 'price'
            JPY
        .field
          .inputs
            = f.check_box :transportation_provided
            = f.label :transportation_provided
        .field
          .inputs
            = f.check_box :hotel_provided
            = f.label :hotel_provided
        .actions
          = f.submit

app/views/bookings/show.html.haml
.section.header
  .container-fluid
    %h1= t '.booking', :artist => @booking.bookee.name # Booking #{@booking.bookee.name}
    
.section.details
  .container-fluid
    .progress
      .progress_box.done
        %h2
          %span 1
          = t '.offer' # Offer
        %p
          %i.fa.fa-check
          = t '.notified', :artist => @booking.bookee.name ##{@booking.bookee.name} has been notified
      .progress_box{:class => "#{@booking.bookee_confirmed_at ? 'done' : 'active'}"}
        %h2 
          %span 2
          = t '.confirmation' # Confirmation
        - if @booking.bookee_confirmed_at
          %p 
            %i.fa.fa-check
            = t '.accepted', :artist => @booking.bookee.name # %{artist} has accepted the offer.
        - else
          %p
            %i.fa.fa-hourglass
            = t '.waiting', :artist => @booking.bookee.name # Waiting for #{@booking.bookee.name}
      .progress_box
        %h2
          %span 3
          = t '.payment' # Payment
        - if @booking.bookee_confirmed_at && @booking.payment.confirmed
          %p= t '.payment_received' # Payment received.
        - elsif @booking.bookee_confirmed_at
          %p= t '.waiting_for_payment' # Waiting for payment  
        - elsif @current_user == @booking.booker
          %p= t '.waiting_for_confirmation', :artist => @booking.bookee.name # You can make the payment after #{@booking.bookee.name} confirmed the offer.
      .progress_box
        %h2
          %span 4
          = t '.done'
        %p= t '.have_fun' #Have fun at the event.
    
    .nice_form.offer_details
      %h2= t '.offer_details' #Offer Details
      .field
        %label= t '.event'
        .inputs
          %p
            = t '.date'
            = @booking.event.start_at
          %p= link_to t('.show_event'), @booking.event
      .field
        %label= t '.guarantee'
        .inputs
          %p ¥‎ #{@booking.price} #{@booking.currency}
          - if @booking.hotel_provided
            %p
              %i.fa.fa-check
              = t '.hotel_provided'
          - else
            %p
              %i.fa.fa-alert
              %strike= t '.hotel_provided'
          - if @booking.transportation_provided
            %p
              %i.fa.fa-check
              = t '.transportation_provided'
          - else
            %p
              %i.fa.fa-warning
              %strike= t '.transportation_provided'
      - if @booking.bookee.managed_by?(@current_user)
        - if !@booking.bookee_confirmed_at
          .field
            .inputs
              = link_to t('.accept_offer'), booking_path(@booking, :booking => {:accept => true}), :method => 'PUT', :class => 'button'
    
    
  
        