config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :bookings
  resources :venues
  resources :artists
  resources :events
  resources :pages
  resource :session do
    get :link_calendar, :on => :member
  end
  resources :goals
  resources :payments, :param => :transaction_id
  resources :funds
  resources :users
  resources :uploads

  get '/auth/:provider/callback', to: 'sessions#create'
  
  root :to => 'pages#index'
  #root :to => 'funds#index'
end

app/models/fund.rb
# == Schema Information
#
# Table name: funds
#
#  id         :integer          not null, primary key
#  name       :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Fund < ApplicationRecord
  include Translatable

  belongs_to :user
  has_many :payments
  has_many :goals

  accepts_translations_for :description
  accepts_nested_attributes_for :goals, :allow_destroy => true

  first_user = User.where(:email => 'hello@newsoundforjapan.com').first_or_create(:password => 'ilovemusic', :password_confirmation => 'ilovemusic')
  Fund.where(:id => 1).first_or_create(:name => 'The Sound Check', :user_id => first_user.id)
  
  def payment_average
    (payments.where(:confirmed => true).average(:amount) || 0).round
  end
end

app/controllers/funds_controller.rb
# == Schema Information
#
# Table name: funds
#
#  id         :integer          not null, primary key
#  name       :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class FundsController < ApplicationController
  before_action :set_fund, only: [:show, :edit, :update, :destroy]

  # GET /funds
  # GET /funds.json
  def index
    @funds = Fund.all
    @fund = Fund.last
    render :show
  end

  # GET /funds/1
  # GET /funds/1.json
  # def show
  # end
  #
  # # GET /funds/new
  # def new
  #   @fund = Fund.new
  # end
  #
  # # GET /funds/1/edit
  # def edit
  # end
  #
  # # POST /funds
  # # POST /funds.json
  # def create
  #   @fund = Fund.new(fund_params)
  #
  #   respond_to do |format|
  #     if @fund.save
  #       format.html { redirect_to @fund, notice: 'Fund was successfully created.' }
  #       format.json { render :show, status: :created, location: @fund }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @fund.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # PATCH/PUT /funds/1
  # PATCH/PUT /funds/1.json
  def update
    return unless @fund.user == @current_user
    
    respond_to do |format|
      if @fund.update(fund_params)
        format.html { redirect_to @fund, notice: 'Fund was successfully updated.' }
        format.json { render :show, status: :ok, location: @fund }
      else
        format.html { render :edit }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end
  #
  # # DELETE /funds/1
  # # DELETE /funds/1.json
  # def destroy
  #   @fund.destroy
  #   respond_to do |format|
  #     format.html { redirect_to funds_url, notice: 'Fund was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fund
      @fund = Fund.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fund_params
      params.require(:fund).permit(:name, :description_ja, :description_en, :goals_attributes => [:name, :amount, :currency, :retained_image, :_destroy, :id, :description_ja, :description_en])
    end
end

app/helpers/funds_helper.rb
# == Schema Information
#
# Table name: funds
#
#  id         :integer          not null, primary key
#  name       :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module FundsHelper
end

app/views/funds/_form.html.haml
= form_for(fund) do |f|
  - if fund.errors.any?
    #error_explanation
      %h2
        = pluralize(fund.errors.count, "error")
        = t('.prohibited_this_fund_from_bein')
      %ul
        - fund.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.translated_text_area :description
  .goals
    = f.fields_for :goals do |builder|
      = render 'goal_fields', :f => builder
    = link_to_add_fields 'Add Goal', f, :goals
  .actions
    = f.submit

app/views/funds/_goal_fields.html.haml
%fieldset.inline_fields.goal
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :amount
    = f.text_field :amount
  .field
    = f.label :image
    = f.image_upload_field :image
  .field
    = f.translated_text_area :description
  = f.hidden_field :currency, :value => 'JPY'
  = f.hidden_field :_destroy
  = link_to "Remove", '#', :class => 'remove_fields'

app/views/funds/edit.html.haml
.main_section
  .wrap.container-fluid
    .row
      .col-xs-12
        = render 'form', fund: @fund
        = link_to t('.back'), @fund

app/views/funds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Funds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @funds.each do |fund| %>
      <tr>
        <td><%= fund.name %></td>
        <td><%= link_to 'Show', fund %></td>
        <td><%= link_to 'Edit', edit_fund_path(fund) %></td>
        <td><%= link_to 'Destroy', fund, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fund', new_fund_path %>

app/views/funds/new.html.erb
<h1>New Fund</h1>

<%= render 'form', fund: @fund %>

<%= link_to 'Back', funds_path %>

app/views/funds/show.html.haml
.main_section
  .wrap.container-fluid
    - if @current_user == @fund.user
      = link_to t('.edit'), edit_fund_path(@fund), :class => 'edit_page_link'
    .row
      .col-xs-12
        = sanitize @fund.description
.goals_section
  .wrap.container-fluid
    .row
      .col-xs-12
        %h1= @fund.name
        %p= t('.current_goals')
        - @fund.goals.each do |goal|
          .goal
            = image_tag goal.image.thumb('300x300#').url, :class => 'goal_image'
            .goal_info
              %h1= goal.name
              .goal_progress
                .bar_wrapper
                  .bar{:style => "width: #{goal.progress_percent}%", :class => "#{'done' if goal.progress_percent >= 100}"}
                .collected_amount 
                  %span.progress ¥#{number_with_delimiter(goal.collected_amount)}
                  %span.dash /
                  %span.total ¥#{number_with_delimiter(goal.amount)}
                .percent{:class => "#{'done' if goal.progress_percent >= 100}"} #{goal.progress_percent}%
              %p= raw goal.description
.sponsors_section
  .wrap.container-fluid
    .row
      .col-xs-12
        %h1 Sponsors
        .pay_more
          = fa_icon 'info-circle'
          %p= t('.pay_more', :average => number_with_delimiter(@fund.payment_average))
        - @fund.payments.paid.published.each do |sponsor_payment|
          = link_to image_tag(sponsor_payment.image.thumb('200x200#').url), sponsor_payment.url
 


- payment = Payment.new(:fund => @fund, :amount => 1000)
.pay_section
  .wrap.container-fluid
    .row
      .col-xs-12
        
        = form_for payment, :html => {:class => 'purchase_form'} do |f|
          
          .section.name
            = t('.be_a_part_of_bfundnameb_html', :fundname => (@fund.name))
            
          .section.amount
            %label= t('.pay_what_you_want')
            .toggle_button{':class' => '{active: payment.amount == 1000}', '@click' => 'payment.amount = 1000;custom=false'}= t('.¥‎1000')
            .toggle_button{':class' => '{active: payment.amount == 2000}', '@click' => 'payment.amount = 2000;custom=false'}= t('.¥‎2000')
            .toggle_button{':class' => '{active: payment.amount == 5000}', '@click' => 'payment.amount = 5000;custom=false'}= t('.¥‎5000')
            .toggle_button{'v-show' => '!custom', '@click' => 'custom = true'}= t('.custom_amount')
            = f.text_field :amount, 'v-show' => 'custom', 'v-model' => 'payment.amount', :class => 'amount_field'
            %span.minimum(v-show='custom')= t '.minimum'
          .section.distribution
            %label= t('.where_your_money_will_go')
            %p
              = t('.to_artists')
            %p
              = t('.to_organizers')
            .with_popup
              %span.dashed= t('.customize_distribution')
              %aside= t('.coming_soon')
          -# .section.identity
          -#   %label= t('.make_your_contribution_public')
          -#   .toggle_button{':class' => '{active: payment.public}', '@click' => 'payment.public = true'}= t('.yes')
          -#   .toggle_button{':class' => '{active: !payment.public}', '@click' => 'payment.public = false'}= t('.no')
          .section.email
            = f.fields_for :user do |uf|
              %label= t('.email')
              = uf.text_field :email, 'v-model' => 'email', :class => 'email_field'
              %p= t('.we_will_send_a_confirmation_wi')
          .section.payment
            .pay_with_stripe
              = fa_icon 'credit-card-alt'
              = t('.pay_with_card')
            .refund_policy
              = fa_icon 'lock'
              = t('.will_be_refunded')
        .payment_info= t '.payment_info'
        
        
        

= form_for @fund.payments.new, :html => {:id => 'payment_form'} do |f|
  = f.hidden_field :fund_id
  = hidden_field_tag :gateway, 'stripe'
  = hidden_field_tag :amount, ''
  = hidden_field_tag :currency, ''
  = hidden_field_tag :email
  = hidden_field_tag :public
  = hidden_field_tag :stripeToken
= javascript_include_tag 'https://checkout.stripe.com/checkout.js'

:coffee

  formvue = new Vue
    el: '.purchase_form'
    data:
      custom: false
      payment: #{payment.to_json}
      email: '#{@current_user.try(:email)}'
    watch:
      custom: (old, newVal) ->
        $('.amount_field').focus() if old

  delay 1000, ->
    handler = StripeCheckout.configure
      key: #{ENV['STRIPE_PUBLIC_KEY'].to_json}
      image: #{asset_path('logo.png').to_json}
      name: #{@fund.name.to_json}
      description: 'New Sound For Japan Fund'
      'allow-remember-me': false
      locale: #{I18n.locale.to_json}
      token: (token) ->
        $('#payment_form [name=amount]').val formvue.payment.amount
        $('#payment_form [name=public]').val formvue.payment.public
        $('#payment_form [name=currency]').val 'jpy'
        $('#payment_form [name=stripeToken]').val token.id
        $('#payment_form [name=email]').val token.email
        $('#payment_form').submit()
    $('.pay_with_stripe').on 'click', (e) ->
      amount = formvue.payment.amount
      return alert(#{t('.minimum').to_json}) if amount < 50
      handler.open
        amount: formvue.payment.amount
        currency: 'jpy'
        email: formvue.email
      e.preventDefault()