config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :bookings
  resources :venues
  resources :artists
  resources :events
  resources :pages
  resource :session do
    get :link_calendar, :on => :member
  end
  resources :goals
  resources :payments, :param => :transaction_id
  resources :funds
  resources :users
  resources :uploads

  get '/auth/:provider/callback', to: 'sessions#create'
  
  root :to => 'pages#index'
  #root :to => 'funds#index'
end

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %title New Sound For Japan
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:property => "og:url", :content => request.url }
    %meta{:property => "og:type", :content => "article" }
    %meta{:property => "og:title", :content => "New Sound For Japan" }
    %meta{:property => "og:description", :content => "Enjoy Japan. Enjoy the Sound. We're bringing back the good shit." }
    %meta{:property => "og:image", :content => asset_url('logo.png') }
  %body.application{:class => "#{params[:controller]} #{params[:action]}"}
    :coffee
      window.locale = #{I18n.locale.to_json}
    = yield :before_content if content_for? :before_content
    %header

      .user_area
        - if @current_user && @current_user.persisted?
          - if @current_user.image
            = image_tag @current_user.image.thumb('200x200').url, :class => 'profile_image'
          - else
            %img.profile_image
          = link_to @current_user.display_name, @current_user
          = link_to "Log out", session_path, :method => :delete
        - else
          .signed_out
            = link_to "Log in", new_session_path, :class => 'email'
            = link_to '/auth/facebook', :class => 'facebook' do
              %i.fa.fa-facebook
              Log in
            = link_to new_user_path, :class => 'sign_up' do
              %i.fa.fa-envelope
              Sign up
      .language_select
        = link_to t('en'), '?locale=en', :class => ('active' if I18n.locale == :en)
        = link_to t('ja'), '?locale=ja', :class => ('active' if I18n.locale == :ja)
      .small_logo
        = link_to image_tag('newsoundforjapantext2.png'), root_url
        Alpha
    %nav
      %ul
        
        = link_to artists_path do
          %li.item{:class => "#{'on' if params[:controller] == 'artists'}"} 
            %i.fa.fa-user
            Artists
        = link_to venues_path do
          %li.item{:class => "#{'on' if params[:controller] == 'venues'}"} 
            %i.fa.fa-home
            Venues
        = link_to events_path do
          %li.item{:class => "#{'on' if params[:controller] == 'events'}"} 
            %i.fa.fa-heart
            Events
        - if @current_user && @current_user.user_relations.any? || @current_user.bookings.active.count > 0
          %li.title Management
        - @current_user.user_relations.each do |relation|
          = link_to relation.relative do
            %li.item
              - if relation.relative.events.upcoming.count > 0
                .badge= relation.relative.events.upcoming.count
              = relation.relative.name
        - if @current_user.bookings.active.count > 0
          = link_to bookings_url do
            %li.item
              .badge= @current_user.bookings.active.count
              Bookings
    %main
      = alert
      = notice
      - if @current_user && @current_user.persisted? && !@current_user.identities.stripe.any?
        .action_required
          %i.fa.fa-warning
          = t '.connect_stripe'
          = link_to '/auth/stripe_connect' do
            = image_tag 'stripe-connect.png'
      .content
        
        = yield
    %footer
      .container-fluid
        .row
          .col-xs-6
            %p New Sound For Japan is your personal agent.
            %p
              Copyright 2016
              = link_to "Stefan Corporation", 'http://stefan.co.jp'
          .col-xs-6
            %p
              Contact:
              %a(href="mailto:hello@newsoundforjapan.com") hello@newsoundforjapan.com